Feature3 character traits
Hdems/HubertDems pull request #6
Opened 2020-06-27 20:39 UTC by Hdems

2020-06-27 21:24 UTC, Hdems commented on index.md
> + **(430 – 425 v. Chr.) Schüler des Sokrates
modified

2020-06-28 12:55 UTC, SanJSp requested changes

2020-06-28 12:55 UTC, SanJSp commented on index.md
> + **(um 240 – 150 v. Chr.), Stoiker
Hier sollte zum Beispiel
```
* Sokrates
* Pythagoras von Samos
```

und so weiter stehen. Einfach ein Leerzeichen nach den Sternen einfügen.

Liebe Grüße  
Sandro

2020-06-29 09:45 UTC, Hdems commented on index.md
> + **(um 240 – 150 v. Chr.), Stoiker
ich habe jetzt mein index.md datei schon geärndet aber wie kann ich das neu pullen oder ein neues check machen?

2020-06-30 08:37 UTC, Hdems reviewed
Konflit gelöst

2020-06-30 08:38 UTC, closed without merging